"""
Project scaffold — Creates a ttt.project.toml with sensible defaults.
"""

import os
from dataclasses import dataclass
from typing import Optional


# ── Default project manifest content ─────────────────────────────────────

_PROJECT_TEMPLATE = """\
# TTT Project Configuration
# Generated by `ttt init`. Customize as needed.
# Docs: https://github.com/zmovirzynski/TTT-Tibia-TFS-Transpiler

[project]
name = "{name}"
source_version = "{source_version}"
target_version = "{target_version}"

# ── Migration presets ────────────────────────────────────────────────────
# Profiles define common migration configurations.
# Activate a profile with: ttt migrate-server --profile <name>

[profiles.default]
steps = ["convert", "fix", "analyze", "doctor", "docs"]
html_diff = true
verbose = false

[profiles.quick]
# Fast check: convert + lint only, no docs generation
steps = ["convert", "fix"]
html_diff = false
verbose = false

[profiles.full]
# Full pipeline with verbose output
steps = ["convert", "fix", "analyze", "doctor", "docs"]
html_diff = true
verbose = true

# ── Paths ────────────────────────────────────────────────────────────────

[paths]
input = "{input_dir}"
output = "{output_dir}"

# ── Lint settings (override config.toml) ─────────────────────────────────

[lint]
disable = []
# enable = ["deprecated-api", "missing-return"]

# ── Fix settings ─────────────────────────────────────────────────────────

[fix]
dry_run = true
backup = false

# ── Plugins ──────────────────────────────────────────────────────────────
# Load custom mapping packs or lint rules from local paths.
# See docs for pack format.

# [plugins]
# mappings = ["./custom/mappings.toml"]
# rules = ["./custom/rules.py"]
"""


@dataclass
class InitResult:
    """Result of project initialization."""

    created: bool = False
    path: str = ""
    error: str = ""
    already_exists: bool = False


def init_project(
    directory: str,
    *,
    name: Optional[str] = None,
    source_version: str = "tfs03",
    target_version: str = "revscript",
    input_dir: str = "./data",
    output_dir: str = "./output",
    force: bool = False,
) -> InitResult:
    """
    Scaffold a ``ttt.project.toml`` in *directory*.

    Returns an :class:`InitResult` describing what happened.
    """
    directory = os.path.abspath(directory)
    filepath = os.path.join(directory, "ttt.project.toml")

    if os.path.exists(filepath) and not force:
        return InitResult(
            created=False,
            path=filepath,
            already_exists=True,
            error="ttt.project.toml already exists (use --force to overwrite)",
        )

    if name is None:
        name = os.path.basename(directory) or "my-server"

    content = _PROJECT_TEMPLATE.format(
        name=name,
        source_version=source_version,
        target_version=target_version,
        input_dir=input_dir,
        output_dir=output_dir,
    )

    os.makedirs(directory, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return InitResult(created=True, path=filepath)


def load_project_config(directory: Optional[str] = None):
    """
    Load ``ttt.project.toml`` from *directory* (or search upward from cwd).

    Returns the parsed dict or an empty dict if not found / unparseable.
    """
    try:
        import tomllib
    except ImportError:
        return {}

    if directory:
        candidate = os.path.join(os.path.abspath(directory), "ttt.project.toml")
        if os.path.exists(candidate):
            with open(candidate, "rb") as f:
                return tomllib.load(f)
        return {}

    # Search upward
    cwd = os.getcwd()
    for d in [cwd, *_parents(cwd)]:
        candidate = os.path.join(d, "ttt.project.toml")
        if os.path.exists(candidate):
            with open(candidate, "rb") as f:
                return tomllib.load(f)
    return {}


def get_profile(project_config: dict, profile_name: str = "default") -> dict:
    """Extract a named profile from a loaded project config."""
    return project_config.get("profiles", {}).get(profile_name, {})


def _parents(path: str):
    """Yield parent directories up to the root."""
    parent = os.path.dirname(path)
    while parent != path:
        yield parent
        path, parent = parent, os.path.dirname(parent)
