"""
HTML templates for docs generator — embedded CSS, no external dependencies.

Provides:
  - index page
  - category page
  - script detail page
  - full CSS embedded in each page
"""

import re


# ---------------------------------------------------------------------------
# CSS (common)
# ---------------------------------------------------------------------------

_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, monospace;
  background: #1e1e2e; color: #cdd6f4; padding: 0; line-height: 1.6;
}
a { color: #89b4fa; text-decoration: none; }
a:hover { text-decoration: underline; }
.container { max-width: 1100px; margin: 0 auto; padding: 20px; }

/* Nav */
nav {
  background: #181825; border-bottom: 2px solid #313244;
  padding: 12px 20px; margin-bottom: 20px;
}
nav .brand { font-size: 18px; font-weight: bold; color: #89b4fa; margin-right: 30px; }
nav a { margin-right: 16px; color: #a6adc8; font-size: 14px; }
nav a:hover, nav a.active { color: #89b4fa; }

/* Header */
h1 { color: #89b4fa; margin-bottom: 5px; font-size: 28px; }
h2 { color: #cba6f7; margin: 20px 0 10px 0; font-size: 22px; }
h3 { color: #f5c2e7; margin: 15px 0 8px 0; font-size: 18px; }
.subtitle { color: #6c7086; margin-bottom: 20px; font-size: 14px; }

/* Stats grid */
.stats {
  display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
  gap: 12px; margin-bottom: 24px;
}
.stat-box {
  background: #313244; border-radius: 8px; padding: 16px; text-align: center;
  border-left: 3px solid #89b4fa; transition: transform 0.1s;
}
.stat-box:hover { transform: translateY(-2px); }
.stat-value { font-size: 32px; font-weight: bold; color: #89b4fa; }
.stat-label { color: #6c7086; font-size: 12px; text-transform: uppercase; margin-top: 4px; }

/* Table */
table {
  width: 100%; border-collapse: collapse; background: #313244;
  border-radius: 8px; overflow: hidden; margin-bottom: 20px;
}
th {
  background: #45475a; text-align: left; padding: 10px 14px;
  color: #89b4fa; font-size: 13px; text-transform: uppercase;
  letter-spacing: 0.5px;
}
td { padding: 8px 14px; border-bottom: 1px solid #45475a; font-size: 13px; }
tr:hover { background: #45475a40; }
.badge {
  display: inline-block; padding: 2px 8px; border-radius: 4px;
  font-weight: bold; font-size: 11px;
}
.badge-action { background: #a6e3a1; color: #1e1e2e; }
.badge-movement { background: #fab387; color: #1e1e2e; }
.badge-talkaction { background: #89b4fa; color: #1e1e2e; }
.badge-creature { background: #f38ba8; color: #1e1e2e; }
.badge-global { background: #cba6f7; color: #1e1e2e; }
.badge-npc { background: #94e2d5; color: #1e1e2e; }
.badge-spell { background: #f9e2af; color: #1e1e2e; }

/* Code block */
pre {
  background: #181825; border: 1px solid #313244; border-radius: 8px;
  padding: 16px; overflow-x: auto; font-size: 13px; line-height: 1.5;
  margin: 10px 0 20px 0; color: #cdd6f4;
}
code { font-family: 'Cascadia Code', 'Fira Code', Consolas, monospace; }

/* Detail card */
.detail-card {
  background: #313244; border-radius: 8px; padding: 20px; margin-bottom: 16px;
}
.detail-card .meta { color: #6c7086; font-size: 13px; margin-bottom: 8px; }
.detail-card .meta span { margin-right: 16px; }

/* Footer */
footer {
  text-align: center; color: #6c7086; font-size: 12px;
  padding: 20px 0; border-top: 1px solid #313244; margin-top: 40px;
}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _html_escape(text: str) -> str:
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def _nav(active: str = "") -> str:
    links = [
        ("index.html", "Overview"),
        ("actions.html", "Actions"),
        ("movements.html", "Movements"),
        ("talkactions.html", "TalkActions"),
        ("creaturescripts.html", "CreatureScripts"),
        ("globalevents.html", "GlobalEvents"),
        ("npcs.html", "NPCs"),
        ("spells.html", "Spells"),
    ]
    parts = ['<nav><span class="brand">TTT Docs</span>']
    for href, label in links:
        cls = ' class="active"' if label.lower() == active.lower() else ""
        parts.append(f'<a href="{href}"{cls}>{label}</a>')
    parts.append("</nav>")
    return "".join(parts)


def _page(title: str, body: str, active: str = "") -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_html_escape(title)} - TTT Server Docs</title>
<style>{_CSS}</style>
</head>
<body>
{_nav(active)}
<div class="container">
{body}
</div>
<footer>Generated by TTT &mdash; OTServer Developer Toolkit</footer>
</body>
</html>"""


def _badge(category: str) -> str:
    badge_map = {
        "actions": "action",
        "movements": "movement",
        "talkactions": "talkaction",
        "creaturescripts": "creature",
        "globalevents": "global",
        "npcs": "npc",
        "spells": "spell",
    }
    cls = badge_map.get(category, "action")
    label = category.replace("scripts", "").replace("events", "").capitalize()
    return f'<span class="badge badge-{cls}">{_html_escape(label)}</span>'


# ---------------------------------------------------------------------------
# Index page
# ---------------------------------------------------------------------------

def render_index(report) -> str:
    """Render the main index page."""
    cats = report.categories
    stats_html = ""
    for cat_name, entries in cats.items():
        if not entries:
            continue
        label = cat_name.replace("scripts", " Scripts").replace("events", " Events").title()
        stats_html += f"""
    <div class="stat-box">
      <div class="stat-value">{len(entries)}</div>
      <div class="stat-label"><a href="{cat_name}.html">{_html_escape(label)}</a></div>
    </div>"""

    # Recent entries table (first 20 across all categories)
    all_entries = []
    for cat_name, entries in cats.items():
        for e in entries:
            all_entries.append(e)
    rows = ""
    for entry in all_entries[:20]:
        script_link = f'<a href="detail_{_safe_filename(entry.category, entry.name)}.html">{_html_escape(entry.name)}</a>'
        rows += f"""
      <tr>
        <td>{_badge(entry.category)}</td>
        <td>{script_link}</td>
        <td>{_html_escape(entry.script)}</td>
        <td>{_html_escape(entry.description[:80])}</td>
      </tr>"""

    body = f"""
  <h1>Server Documentation</h1>
  <p class="subtitle">Directory: {_html_escape(report.directory)} &mdash; {report.total_entries} entries documented</p>

  <div class="stats">
    <div class="stat-box">
      <div class="stat-value">{report.total_entries}</div>
      <div class="stat-label">Total Entries</div>
    </div>
    {stats_html}
  </div>

  <h2>All Entries</h2>
  <table>
    <thead>
      <tr><th>Type</th><th>Name</th><th>Script</th><th>Description</th></tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
"""
    return _page("Overview", body, active="Overview")


# ---------------------------------------------------------------------------
# Category page
# ---------------------------------------------------------------------------

def render_category(category: str, entries) -> str:
    """Render a category listing page."""
    title = category.replace("scripts", " Scripts").replace("events", " Events").title()

    # Build header columns based on category
    extra_cols = _category_columns(category)
    header = "<th>Name</th><th>Script</th>"
    for col_name, _ in extra_cols:
        header += f"<th>{_html_escape(col_name)}</th>"
    header += "<th>Description</th>"

    rows = ""
    for entry in entries:
        link = f'<a href="detail_{_safe_filename(entry.category, entry.name)}.html">{_html_escape(entry.name)}</a>'
        row = f"<td>{link}</td><td>{_html_escape(entry.script)}</td>"
        for _, attr_key in extra_cols:
            val = entry.attributes.get(attr_key, "")
            row += f"<td>{_html_escape(str(val))}</td>"
        row += f"<td>{_html_escape(entry.description[:100])}</td>"
        rows += f"<tr>{row}</tr>\n"

    body = f"""
  <h1>{_html_escape(title)}</h1>
  <p class="subtitle">{len(entries)} entries</p>

  <table>
    <thead><tr>{header}</tr></thead>
    <tbody>{rows}</tbody>
  </table>
"""
    return _page(title, body, active=title.split()[0])


def _category_columns(category: str):
    """Return extra columns for a category: list of (label, attr_key)."""
    if category == "actions":
        return [("Item ID", "itemid"), ("Action ID", "actionid")]
    elif category == "movements":
        return [("Type", "type"), ("Item ID", "itemid"), ("Action ID", "actionid")]
    elif category == "talkactions":
        return [("Words", "words"), ("Access", "access")]
    elif category == "creaturescripts":
        return [("Event", "type"), ("Name", "name")]
    elif category == "globalevents":
        return [("Type", "type"), ("Interval", "interval")]
    elif category == "npcs":
        return [("Keywords", "keywords"), ("Health", "health")]
    elif category == "spells":
        return [("Mana", "mana"), ("Level", "lvl"), ("Words", "words")]
    return []


# ---------------------------------------------------------------------------
# Detail page
# ---------------------------------------------------------------------------

def render_detail(entry) -> str:
    """Render a script detail page."""
    title = entry.name

    # Attributes list
    attrs_html = ""
    if entry.attributes:
        attrs_html = '<div class="meta">'
        for k, v in entry.attributes.items():
            attrs_html += f'<span><strong>{_html_escape(k)}:</strong> {_html_escape(str(v))}</span>'
        attrs_html += "</div>"

    # Code block
    code_html = ""
    if entry.lua_content:
        code_html = f"<h3>Source Code</h3>\n<pre><code>{_html_escape(entry.lua_content)}</code></pre>"

    body = f"""
  <h1>{_badge(entry.category)} {_html_escape(entry.name)}</h1>
  <p class="subtitle">
    Script: {_html_escape(entry.script)} &mdash;
    Category: {_html_escape(entry.category)}
  </p>

  <div class="detail-card">
    {attrs_html}
    <p>{_html_escape(entry.description)}</p>
  </div>

  {code_html}
"""
    cat_title = entry.category.replace("scripts", " Scripts").replace("events", " Events").title()
    return _page(title, body, active=cat_title.split()[0])


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_filename(category: str, name: str) -> str:
    """Create a filesystem-safe filename from category + name."""
    safe = re.sub(r'[^\w\-]', '_', f"{category}_{name}")
    return safe[:80]
