"""Mapeamento de constantes TFS 0.3/0.4 → 1.x."""

BOOLEAN_CONSTANTS = {
    "TRUE": "true",
    "FALSE": "false",
    "LUA_ERROR": "false",
    "LUA_NO_ERROR": "true",
    "LUA_NULL": "nil",
    "LUA_TRUE": "true",
    "LUA_FALSE": "false",
}

TALK_TYPES = {
    "TALKTYPE_SAY": "TALKTYPE_SAY",
    "TALKTYPE_WHISPER": "TALKTYPE_WHISPER",
    "TALKTYPE_YELL": "TALKTYPE_YELL",
    "TALKTYPE_ORANGE_1": "TALKTYPE_MONSTER_SAY",
    "TALKTYPE_ORANGE_2": "TALKTYPE_MONSTER_YELL",
    "TALKTYPE_PRIVATE": "TALKTYPE_PRIVATE_FROM",
    "TALKTYPE_BROADCAST": "TALKTYPE_BROADCAST",
    "TALKTYPE_PRIVATE_RED": "TALKTYPE_PRIVATE_RED_FROM",
    "TALKTYPE_CHANNEL_Y": "TALKTYPE_CHANNEL_Y",
    "TALKTYPE_CHANNEL_O": "TALKTYPE_CHANNEL_O",
    "TALKTYPE_CHANNEL_R1": "TALKTYPE_CHANNEL_R1",
    "TALKTYPE_CHANNEL_R2": "TALKTYPE_CHANNEL_R2",
    "TALKTYPE_MONSTER": "TALKTYPE_MONSTER_SAY",
    "TALKTYPE_MONSTER_SAY": "TALKTYPE_MONSTER_SAY",
    "TALKTYPE_MONSTER_YELL": "TALKTYPE_MONSTER_YELL",
}

MESSAGE_TYPES = {
    "MESSAGE_STATUS_CONSOLE_BLUE": "MESSAGE_STATUS_CONSOLE_BLUE",
    "MESSAGE_STATUS_CONSOLE_RED": "MESSAGE_STATUS_CONSOLE_RED",
    "MESSAGE_EVENT_ORANGE": "MESSAGE_EVENT_ORANGE",
    "MESSAGE_STATUS_DEFAULT": "MESSAGE_STATUS_DEFAULT",
    "MESSAGE_STATUS_WARNING": "MESSAGE_STATUS_WARNING",
    "MESSAGE_INFO_DESCR": "MESSAGE_INFO_DESCR",
    "MESSAGE_EVENT_DEFAULT": "MESSAGE_EVENT_DEFAULT",
    "MESSAGE_EVENT_ADVANCE": "MESSAGE_EVENT_ADVANCE",
    "MESSAGE_STATUS_SMALL": "MESSAGE_STATUS_SMALL",
    "MESSAGE_STATUS_CONSOLE_ORANGE": "MESSAGE_STATUS_CONSOLE_ORANGE",
    # 0.3 specific names
    "MSG_STATUS_CONSOLE_BLUE": "MESSAGE_STATUS_CONSOLE_BLUE",
    "MSG_STATUS_CONSOLE_RED": "MESSAGE_STATUS_CONSOLE_RED",
    "MSG_EVENT_ORANGE": "MESSAGE_EVENT_ORANGE",
    "MSG_STATUS_DEFAULT": "MESSAGE_STATUS_DEFAULT",
    "MSG_STATUS_WARNING": "MESSAGE_STATUS_WARNING",
    "MSG_INFO_DESCR": "MESSAGE_INFO_DESCR",
    "MSG_EVENT_DEFAULT": "MESSAGE_EVENT_DEFAULT",
    "MSG_EVENT_ADVANCE": "MESSAGE_EVENT_ADVANCE",
    "MSG_STATUS_SMALL": "MESSAGE_STATUS_SMALL",
    "MSG_STATUS_CONSOLE_ORANGE": "MESSAGE_STATUS_CONSOLE_ORANGE",
    # Numeric to constant (some 0.3 scripts use raw numbers)
}

# COMBAT / DAMAGE CONSTANTS

COMBAT_TYPES = {
    "COMBAT_PHYSICALDAMAGE": "COMBAT_PHYSICALDAMAGE",
    "COMBAT_ENERGYDAMAGE": "COMBAT_ENERGYDAMAGE",
    "COMBAT_EARTHDAMAGE": "COMBAT_EARTHDAMAGE",
    "COMBAT_FIREDAMAGE": "COMBAT_FIREDAMAGE",
    "COMBAT_UNDEFINEDDAMAGE": "COMBAT_UNDEFINEDDAMAGE",
    "COMBAT_LIFEDRAIN": "COMBAT_LIFEDRAIN",
    "COMBAT_MANADRAIN": "COMBAT_MANADRAIN",
    "COMBAT_HEALING": "COMBAT_HEALING",
    "COMBAT_DROWNDAMAGE": "COMBAT_DROWNDAMAGE",
    "COMBAT_ICEDAMAGE": "COMBAT_ICEDAMAGE",
    "COMBAT_HOLYDAMAGE": "COMBAT_HOLYDAMAGE",
    "COMBAT_DEATHDAMAGE": "COMBAT_DEATHDAMAGE",
}

CONDITION_TYPES = {
    "CONDITION_POISON": "CONDITION_POISON",
    "CONDITION_FIRE": "CONDITION_FIRE",
    "CONDITION_ENERGY": "CONDITION_ENERGY",
    "CONDITION_LIFEDRAIN": "CONDITION_BLEEDING",  # changed in 1.x
    "CONDITION_HASTE": "CONDITION_HASTE",
    "CONDITION_PARALYZE": "CONDITION_PARALYZE",
    "CONDITION_OUTFIT": "CONDITION_OUTFIT",
    "CONDITION_INVISIBLE": "CONDITION_INVISIBLE",
    "CONDITION_LIGHT": "CONDITION_LIGHT",
    "CONDITION_MANASHIELD": "CONDITION_MANASHIELD",
    "CONDITION_INFIGHT": "CONDITION_INFIGHT",
    "CONDITION_DRUNK": "CONDITION_DRUNK",
    "CONDITION_EXHAUST": "CONDITION_EXHAUST_WEAPON",  # split in 1.x
    "CONDITION_REGENERATION": "CONDITION_REGENERATION",
    "CONDITION_SOUL": "CONDITION_SOUL",
    "CONDITION_DROWN": "CONDITION_DROWN",
    "CONDITION_MUTED": "CONDITION_MUTED",
    "CONDITION_ATTRIBUTES": "CONDITION_ATTRIBUTES",
    "CONDITION_FREEZING": "CONDITION_FREEZING",
    "CONDITION_DAZZLED": "CONDITION_DAZZLED",
    "CONDITION_CURSED": "CONDITION_CURSED",
    "CONDITION_PACIFIED": "CONDITION_PACIFIED",
    "CONDITION_EXHAUST_COMBAT": "CONDITION_EXHAUST_COMBAT",
    "CONDITION_EXHAUST_HEAL": "CONDITION_EXHAUST_HEAL",
}

SLOT_CONSTANTS = {
    "CONST_SLOT_HEAD": "CONST_SLOT_HEAD",
    "CONST_SLOT_NECKLACE": "CONST_SLOT_NECKLACE",
    "CONST_SLOT_BACKPACK": "CONST_SLOT_BACKPACK",
    "CONST_SLOT_ARMOR": "CONST_SLOT_ARMOR",
    "CONST_SLOT_RIGHT": "CONST_SLOT_RIGHT",
    "CONST_SLOT_LEFT": "CONST_SLOT_LEFT",
    "CONST_SLOT_LEGS": "CONST_SLOT_LEGS",
    "CONST_SLOT_FEET": "CONST_SLOT_FEET",
    "CONST_SLOT_RING": "CONST_SLOT_RING",
    "CONST_SLOT_AMMO": "CONST_SLOT_AMMO",
    # 0.3 name variants
    "SLOT_HEAD": "CONST_SLOT_HEAD",
    "SLOT_NECKLACE": "CONST_SLOT_NECKLACE",
    "SLOT_BACKPACK": "CONST_SLOT_BACKPACK",
    "SLOT_ARMOR": "CONST_SLOT_ARMOR",
    "SLOT_RIGHT": "CONST_SLOT_RIGHT",
    "SLOT_LEFT": "CONST_SLOT_LEFT",
    "SLOT_LEGS": "CONST_SLOT_LEGS",
    "SLOT_FEET": "CONST_SLOT_FEET",
    "SLOT_RING": "CONST_SLOT_RING",
    "SLOT_AMMO": "CONST_SLOT_AMMO",
}

SKULL_CONSTANTS = {
    "SKULL_NONE": "SKULL_NONE",
    "SKULL_YELLOW": "SKULL_YELLOW",
    "SKULL_GREEN": "SKULL_GREEN",
    "SKULL_WHITE": "SKULL_WHITE",
    "SKULL_RED": "SKULL_RED",
    "SKULL_BLACK": "SKULL_BLACK",
    "SKULL_ORANGE": "SKULL_ORANGE",
}

RETURN_VALUES = {
    "RET_NOERROR": "RETURNVALUE_NOERROR",
    "RET_NOTPOSSIBLE": "RETURNVALUE_NOTPOSSIBLE",
    "RET_NOTENOUGHROOM": "RETURNVALUE_NOTENOUGHROOM",
    "RET_PLAYERISPZLOCKED": "RETURNVALUE_PLAYERISPZLOCKED",
    "RET_PLAYERISNOTINVITED": "RETURNVALUE_PLAYERISNOTINVITED",
    "RET_CANNOTTHROW": "RETURNVALUE_CANNOTTHROW",
    "RET_THEREISNOWAY": "RETURNVALUE_THEREISNOWAY",
    "RET_DESTINATIONOUTOFREACH": "RETURNVALUE_DESTINATIONOUTOFREACH",
    "RET_CREATUREBLOCK": "RETURNVALUE_CREATUREBLOCK",
    "RET_NOTMOVEABLE": "RETURNVALUE_NOTMOVEABLE",
    "RET_DROPTWOHANDEDITEM": "RETURNVALUE_DROPTWOHANDEDITEM",
    "RET_BOTHHANDSNEEDTOBEFREE": "RETURNVALUE_BOTHHANDSNEEDTOBEFREE",
    "RET_CANONLYUSEONEWEAPON": "RETURNVALUE_CANONLYUSEONEWEAPON",
    "RET_NEEDEXCHANGE": "RETURNVALUE_NEEDEXCHANGE",
    "RET_CANNOTBEDRESSED": "RETURNVALUE_CANNOTBEDRESSED",
    "RET_PUTTHISOBJECTINYOURHAND": "RETURNVALUE_PUTTHISOBJECTINYOURHAND",
    "RET_PUTTHISOBJECTINBOTHHANDS": "RETURNVALUE_PUTTHISOBJECTINBOTHHANDS",
    "RET_TOOFARAWAY": "RETURNVALUE_TOOFARAWAY",
    "RET_FIRSTGODOWNSTAIRS": "RETURNVALUE_FIRSTGODOWNSTAIRS",
    "RET_FIRSTGOUPSTAIRS": "RETURNVALUE_FIRSTGOUPSTAIRS",
    "RET_CONTAINERNOTENOUGHROOM": "RETURNVALUE_CONTAINERNOTENOUGHROOM",
    "RET_NOTENOUGHCAPACITY": "RETURNVALUE_NOTENOUGHCAPACITY",
    "RET_CANNOTPICKUP": "RETURNVALUE_CANNOTPICKUP",
    "RET_THISISIMPOSSIBLE": "RETURNVALUE_THISISIMPOSSIBLE",
    "RET_DEPOTISFULL": "RETURNVALUE_DEPOTISFULL",
    "RET_CREATUREDOESNOTEXIST": "RETURNVALUE_CREATUREDOESNOTEXIST",
    "RET_CANNOTUSETHISOBJECT": "RETURNVALUE_CANNOTUSETHISOBJECT",
    "RET_PLAYERWITHTHISNAMEISNOTONLINE": "RETURNVALUE_PLAYERWITHTHISNAMEISNOTONLINE",
    "RET_NOTREQUIREDLEVELTOUSERUNE": "RETURNVALUE_NOTREQUIREDLEVELTOUSERUNE",
    "RET_YOUAREALREADYTRADING": "RETURNVALUE_YOUAREALREADYTRADING",
    "RET_THISPLAYERISALREADYTRADING": "RETURNVALUE_THISPLAYERISALREADYTRADING",
    "RET_YOUMAYNOTLOGOUTDURINGAFIGHT": "RETURNVALUE_YOUMAYNOTLOGOUTDURINGAFIGHT",
    "RET_DIRECTPLAYERSHOOT": "RETURNVALUE_DIRECTPLAYERSHOOT",
    "RET_NOTENOUGHLEVEL": "RETURNVALUE_NOTENOUGHLEVEL",
    "RET_NOTENOUGHMAGICLEVEL": "RETURNVALUE_NOTENOUGHMAGICLEVEL",
    "RET_NOTENOUGHMANA": "RETURNVALUE_NOTENOUGHMANA",
    "RET_NOTENOUGHSOUL": "RETURNVALUE_NOTENOUGHSOUL",
    "RET_YOUAREEXHAUSTED": "RETURNVALUE_YOUAREEXHAUSTED",
    "RET_PLAYERISNOTREACHABLE": "RETURNVALUE_PLAYERISNOTREACHABLE",
    "RET_CANONLYUSETHISRUNEITHISAREA": "RETURNVALUE_CANONLYUSETHISRUNEITHISAREA",
    "RET_YOUCANNOTUSETHISITEM": "RETURNVALUE_CANNOTUSETHISOBJECT",
    # RETURNVALUE_ prefix already used in some 0.4 scripts
    "RETURNVALUE_NOERROR": "RETURNVALUE_NOERROR",
    "RETURNVALUE_NOTPOSSIBLE": "RETURNVALUE_NOTPOSSIBLE",
}

DIRECTION_CONSTANTS = {
    "NORTH": "DIRECTION_NORTH",
    "SOUTH": "DIRECTION_SOUTH",
    "EAST": "DIRECTION_EAST",
    "WEST": "DIRECTION_WEST",
    "SOUTHWEST": "DIRECTION_SOUTHWEST",
    "SOUTHEAST": "DIRECTION_SOUTHEAST",
    "NORTHWEST": "DIRECTION_NORTHWEST",
    "NORTHEAST": "DIRECTION_NORTHEAST",
    # Already-prefixed versions stay the same
    "DIRECTION_NORTH": "DIRECTION_NORTH",
    "DIRECTION_SOUTH": "DIRECTION_SOUTH",
    "DIRECTION_EAST": "DIRECTION_EAST",
    "DIRECTION_WEST": "DIRECTION_WEST",
}

MAGIC_EFFECTS = {
    "CONST_ME_DRAWBLOOD": "CONST_ME_DRAWBLOOD",
    "CONST_ME_LOSEENERGY": "CONST_ME_LOSEENERGY",
    "CONST_ME_POFF": "CONST_ME_POFF",
    "CONST_ME_BLOCKHIT": "CONST_ME_BLOCKHIT",
    "CONST_ME_EXPLOSIONAREA": "CONST_ME_EXPLOSIONAREA",
    "CONST_ME_EXPLOSIONHIT": "CONST_ME_EXPLOSIONHIT",
    "CONST_ME_FIREAREA": "CONST_ME_FIREAREA",
    "CONST_ME_YELLOW_RINGS": "CONST_ME_YELLOW_RINGS",
    "CONST_ME_GREEN_RINGS": "CONST_ME_GREEN_RINGS",
    "CONST_ME_HITAREA": "CONST_ME_HITAREA",
    "CONST_ME_TELEPORT": "CONST_ME_TELEPORT",
    "CONST_ME_ENERGYHIT": "CONST_ME_ENERGYHIT",
    "CONST_ME_MAGIC_BLUE": "CONST_ME_MAGIC_BLUE",
    "CONST_ME_MAGIC_RED": "CONST_ME_MAGIC_RED",
    "CONST_ME_MAGIC_GREEN": "CONST_ME_MAGIC_GREEN",
    "CONST_ME_HITBYFIRE": "CONST_ME_HITBYFIRE",
    "CONST_ME_HITBYPOISON": "CONST_ME_HITBYPOISON",
    "CONST_ME_MORTAREA": "CONST_ME_MORTAREA",
    "CONST_ME_SOUND_GREEN": "CONST_ME_SOUND_GREEN",
    "CONST_ME_SOUND_RED": "CONST_ME_SOUND_RED",
    "CONST_ME_POISONAREA": "CONST_ME_POISONAREA",
    "CONST_ME_SOUND_YELLOW": "CONST_ME_SOUND_YELLOW",
    "CONST_ME_SOUND_PURPLE": "CONST_ME_SOUND_PURPLE",
    "CONST_ME_SOUND_BLUE": "CONST_ME_SOUND_BLUE",
    "CONST_ME_SOUND_WHITE": "CONST_ME_SOUND_WHITE",
    "CONST_ME_BUBBLES": "CONST_ME_BUBBLES",
    "CONST_ME_CRAPS": "CONST_ME_CRAPS",
    "CONST_ME_GIFT_WRAPS": "CONST_ME_GIFT_WRAPS",
    "CONST_ME_FIREWORK_YELLOW": "CONST_ME_FIREWORK_YELLOW",
    "CONST_ME_FIREWORK_RED": "CONST_ME_FIREWORK_RED",
    "CONST_ME_FIREWORK_BLUE": "CONST_ME_FIREWORK_BLUE",
    "CONST_ME_STUN": "CONST_ME_STUN",
    "CONST_ME_SLEEP": "CONST_ME_SLEEP",
    "CONST_ME_WATERCREATURE": "CONST_ME_WATERCREATURE",
    "CONST_ME_GROUNDSHAKER": "CONST_ME_GROUNDSHAKER",
    "CONST_ME_HEARTS": "CONST_ME_HEARTS",
    "CONST_ME_FIREATTACK": "CONST_ME_FIREATTACK",
    "CONST_ME_ENERGYAREA": "CONST_ME_ENERGYAREA",
    "CONST_ME_SMALLCLOUDS": "CONST_ME_SMALLCLOUDS",
    "CONST_ME_HOLYDAMAGE": "CONST_ME_HOLYDAMAGE",
    "CONST_ME_BIGCLOUDS": "CONST_ME_BIGCLOUDS",
    "CONST_ME_ICEAREA": "CONST_ME_ICEAREA",
    "CONST_ME_ICETORNADO": "CONST_ME_ICETORNADO",
    "CONST_ME_ICEATTACK": "CONST_ME_ICEATTACK",
    "CONST_ME_STONES": "CONST_ME_STONES",
    "CONST_ME_SMALLPLANTS": "CONST_ME_SMALLPLANTS",
    "CONST_ME_CARNIPHILA": "CONST_ME_CARNIPHILA",
    "CONST_ME_PURPLEENERGY": "CONST_ME_PURPLEENERGY",
    "CONST_ME_YELLOWENERGY": "CONST_ME_YELLOWENERGY",
    "CONST_ME_HOLYAREA": "CONST_ME_HOLYAREA",
    "CONST_ME_BIGPLANTS": "CONST_ME_BIGPLANTS",
    "CONST_ME_CAKE": "CONST_ME_CAKE",
    "CONST_ME_GIANTICE": "CONST_ME_GIANTICE",
    "CONST_ME_WATERSPLASH": "CONST_ME_WATERSPLASH",
    "CONST_ME_PLANTATTACK": "CONST_ME_PLANTATTACK",
    "CONST_ME_TUTORIALARROW": "CONST_ME_TUTORIALARROW",
    "CONST_ME_TUTORIALSQUARE": "CONST_ME_TUTORIALSQUARE",
    # Old numeric references (some 0.3 scripts use these)
    "MAGIC_EFFECT_DRAW_BLOOD": "CONST_ME_DRAWBLOOD",
    "MAGIC_EFFECT_LOSE_ENERGY": "CONST_ME_LOSEENERGY",
    "MAGIC_EFFECT_POFF": "CONST_ME_POFF",
    "MAGIC_EFFECT_TELEPORT": "CONST_ME_TELEPORT",
}

# ITEM / FLUID TYPE CONSTANTS

FLUID_TYPES = {
    "FLUID_NONE": "FLUID_NONE",
    "FLUID_WATER": "FLUID_WATER",
    "FLUID_BLOOD": "FLUID_BLOOD",
    "FLUID_BEER": "FLUID_BEER",
    "FLUID_SLIME": "FLUID_SLIME",
    "FLUID_LEMONADE": "FLUID_LEMONADE",
    "FLUID_MILK": "FLUID_MILK",
    "FLUID_MANAFLUID": "FLUID_MANA",
    "FLUID_MANA": "FLUID_MANA",
    "FLUID_LIFEFLUID": "FLUID_LIFE",
    "FLUID_LIFE": "FLUID_LIFE",
    "FLUID_OIL": "FLUID_OIL",
    "FLUID_URINE": "FLUID_URINE",
    "FLUID_COCONUTMILK": "FLUID_COCONUTMILK",
    "FLUID_WINE": "FLUID_WINE",
    "FLUID_MUD": "FLUID_MUD",
    "FLUID_FRUITJUICE": "FLUID_FRUITJUICE",
    "FLUID_LAVA": "FLUID_LAVA",
    "FLUID_RUM": "FLUID_RUM",
    "FLUID_SWAMP": "FLUID_SWAMP",
    "FLUID_TEA": "FLUID_TEA",
    "FLUID_MEAD": "FLUID_MEAD",
}

# Combine all constants into a single mapping

ALL_CONSTANTS = {}
ALL_CONSTANTS.update(BOOLEAN_CONSTANTS)
ALL_CONSTANTS.update(TALK_TYPES)
ALL_CONSTANTS.update(MESSAGE_TYPES)
ALL_CONSTANTS.update(COMBAT_TYPES)
ALL_CONSTANTS.update(CONDITION_TYPES)
ALL_CONSTANTS.update(SLOT_CONSTANTS)
ALL_CONSTANTS.update(SKULL_CONSTANTS)
ALL_CONSTANTS.update(RETURN_VALUES)
ALL_CONSTANTS.update(DIRECTION_CONSTANTS)
ALL_CONSTANTS.update(MAGIC_EFFECTS)
ALL_CONSTANTS.update(FLUID_TYPES)
