"""Mapeamento de funções TFS 0.3.6 → TFS 1.x."""

PLAYER_GETTERS = {
    "getCreatureName": {
        "method": "getName",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerName": {
        "method": "getName",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerLevel": {
        "method": "getLevel",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerExperience": {
        "method": "getExperience",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerMagLevel": {
        "method": "getMagicLevel",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerVocation": {
        "method": "getVocation",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "chain": ":getId()",
        "note": "-- TTT: Returns Vocation object, auto-chained :getId() for numeric ID",
    },
    "getPlayerSex": {
        "method": "getSex",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerGUID": {
        "method": "getGuid",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerGroupId": {
        "method": "getGroup",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "chain": ":getId()",
        "note": "-- TTT: Returns Group object, auto-chained :getId() for numeric ID",
    },
    "getPlayerAccountId": {
        "method": "getAccountId",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerAccountType": {
        "method": "getAccountType",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerIp": {
        "method": "getIp",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerFlagValue": {
        "method": "hasFlag",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerGuildId": {
        "method": "getGuild",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "chain": ":getId()",
        "note": "-- TTT: Returns Guild object, auto-chained :getId() for numeric ID",
    },
    "getPlayerGuildName": {
        "method": "getGuild",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "chain": ":getName()",
        "note": "-- TTT: Returns Guild object, auto-chained :getName() for name",
    },
    "getPlayerGuildRank": {
        "method": "getGuild",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: Use player:getGuild() and guild ranks API",
    },
    "getPlayerGuildNick": {
        "method": "getGuildNick",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getPlayerPosition": {
        "method": "getPosition",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreaturePosition": {
        "method": "getPosition",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getThingPos": {
        "method": "getPosition",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getThingPosition": {
        "method": "getPosition",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerTown": {
        "method": "getTown",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "chain": ":getId()",
        "note": "-- TTT: Returns Town object, auto-chained :getId() for numeric ID",
    },
    "getPlayerMasterPos": {
        "method": "getTown",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: Use player:getTown():getTemplePosition()",
    },

    "getCreatureHealth": {
        "method": "getHealth",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureMaxHealth": {
        "method": "getMaxHealth",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerHealth": {
        "method": "getHealth",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerMaxHealth": {
        "method": "getMaxHealth",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerMana": {
        "method": "getMana",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerMaxMana": {
        "method": "getMaxMana",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getPlayerFreeCap": {
        "method": "getFreeCapacity",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerSoul": {
        "method": "getSoul",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getPlayerSkill": {
        "method": "getSkillLevel",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerSkillLevel": {
        "method": "getSkillLevel",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerSkillTries": {
        "method": "getSkillTries",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getPlayerItemCount": {
        "method": "getItemCount",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerSlotItem": {
        "method": "getSlotItem",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getPlayerStorageValue": {
        "method": "getStorageValue",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureStorage": {
        "method": "getStorageValue",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getGlobalStorageValue": {
        "method": "getStorageValue",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },

    "getPlayerPremiumDays": {
        "method": "getPremiumDays",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "isPremium": {
        "method": "isPremium",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getPlayerBalance": {
        "method": "getBankBalance",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerMoney": {
        "method": "getMoney",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getCreatureOutfit": {
        "method": "getOutfit",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "canPlayerWearOutfit": {
        "method": "hasOutfit",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getCreatureLookDir": {
        "method": "getDirection",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureLookDirection": {
        "method": "getDirection",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureSpeed": {
        "method": "getSpeed",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureBaseSpeed": {
        "method": "getBaseSpeed",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getCreatureTarget": {
        "method": "getTarget",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureMaster": {
        "method": "getMaster",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureSummons": {
        "method": "getSummons",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },

    "hasCondition": {
        "method": "hasCondition",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getCreatureCondition": {
        "method": "hasCondition",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "hasPlayerConditionInList": {
        "method": "hasCondition",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "getPlayerFood": {
        "method": "getCondition(CONDITION_REGENERATION)",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: In 1.x use player:getCondition(CONDITION_REGENERATION):getTicks() / 1000",
    },

    "getItemName": {
        "method": "getName",
        "obj_type": "item_type",
        "obj_param": None,
        "drop_params": [],
        "custom": "item_type_getter",
    },
    "getItemDescriptions": {
        "method": "getDescription",
        "obj_type": "item_type",
        "obj_param": None,
        "drop_params": [],
        "custom": "item_type_getter",
    },
    "getItemWeight": {
        "method": "getWeight",
        "obj_type": "item_type",
        "obj_param": None,
        "drop_params": [],
        "custom": "item_type_getter",
    },
    "getItemIdByName": {
        "method": "getId",
        "obj_type": "item_type",
        "obj_param": None,
        "drop_params": [],
        "custom": "item_type_by_name",
    },
    "getItemAttribute": {
        "method": "getAttribute",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },

    "isPlayer": {
        "method": None,
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "custom": "type_check",
        "custom_class": "Player",
    },
    "isCreature": {
        "method": None,
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
        "custom": "type_check",
        "custom_class": "Creature",
    },
    "isMonster": {
        "method": None,
        "obj_type": "monster",
        "obj_param": 0,
        "drop_params": [0],
        "custom": "type_check",
        "custom_class": "Monster",
    },
    "isNpc": {
        "method": None,
        "obj_type": "npc",
        "obj_param": 0,
        "drop_params": [0],
        "custom": "type_check",
        "custom_class": "Npc",
    },
    "isSorcerer": {
        "method": "isPromoted",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: Use player:getVocation():getId() to check vocation type",
        "custom": "vocation_check",
    },
    "isDruid": {
        "method": "isPromoted",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: Use player:getVocation():getId() to check vocation type",
        "custom": "vocation_check",
    },
    "isPaladin": {
        "method": "isPromoted",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: Use player:getVocation():getId() to check vocation type",
        "custom": "vocation_check",
    },
    "isKnight": {
        "method": "isPromoted",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: Use player:getVocation():getId() to check vocation type",
        "custom": "vocation_check",
    },
}

# PLAYER ACTION FUNCTIONS (doPlayer*)

PLAYER_ACTIONS = {
    "doPlayerSendTextMessage": {
        "method": "sendTextMessage",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSendCancel": {
        "method": "sendCancelMessage",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSendDefaultCancel": {
        "method": "sendCancelMessage",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerPopupFYI": {
        "method": "popupFYI",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSendChannelMessage": {
        "method": "sendChannelMessage",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerAddItem": {
        "method": "addItem",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerRemoveItem": {
        "method": "removeItem",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerGiveItem": {
        "method": "addItem",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerTakeItem": {
        "method": "removeItem",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doCreatureAddHealth": {
        "method": "addHealth",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerAddHealth": {
        "method": "addHealth",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerAddMana": {
        "method": "addMana",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerAddManaSpent": {
        "method": "addManaSpent",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerAddSoul": {
        "method": "addSoul",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerAddExperience": {
        "method": "addExperience",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerAddSkillTry": {
        "method": "addSkillTries",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerSetStorageValue": {
        "method": "setStorageValue",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "setPlayerStorageValue": {
        "method": "setStorageValue",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doCreatureSetStorage": {
        "method": "setStorageValue",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "setGlobalStorageValue": {
        "method": "setStorageValue",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },

    "doPlayerAddPremiumDays": {
        "method": "addPremiumDays",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerRemovePremiumDays": {
        "method": "removePremiumDays",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerSetBalance": {
        "method": "setBankBalance",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerWithdrawMoney": {
        "method": "removeMoneyBank",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerWithdrawAllMoney": {
        "method": "removeMoneyBank",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: Check correct amount for withdrawAll",
    },
    "doPlayerDepositMoney": {
        "method": "addMoneyBank",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerTransferMoneyTo": {
        "method": "transferMoneyTo",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerAddMoney": {
        "method": "addMoney",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerRemoveMoney": {
        "method": "removeMoney",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerAddOutfit": {
        "method": "addOutfit",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerAddOutfitId": {
        "method": "addOutfitAddon",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerRemoveOutfit": {
        "method": "removeOutfit",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerRemoveOutfitId": {
        "method": "removeOutfitAddon",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doSetCreatureOutfit": {
        "method": "setOutfit",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerSetTown": {
        "method": "setTown",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: In 1.x use player:setTown(Town(townId))",
    },
    "doPlayerSetVocation": {
        "method": "setVocation",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSetSex": {
        "method": "setSex",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSetMaxCapacity": {
        "method": "setCapacity",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doTeleportThing": {
        "method": "teleportTo",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doMoveCreature": {
        "method": "move",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doCreatureSay": {
        "method": "say",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doCreatureSetLookDir": {
        "method": "setDirection",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doCreatureSetLookDirection": {
        "method": "setDirection",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doCreatureSetLookDirOk": {
        "method": "setDirection",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doChangeSpeed": {
        "method": "changeSpeed",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "setCreatureMaxHealth": {
        "method": "setMaxHealth",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doCreatureSetHideHealth": {
        "method": "setHiddenHealth",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doCreatureSetNoMove": {
        "method": "setMoveLocked",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doCreatureSetSkullType": {
        "method": "setSkull",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doRemoveCreature": {
        "method": "remove",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doAddCondition": {
        "method": "addCondition",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doRemoveCondition": {
        "method": "removeCondition",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doTargetCombatHealth": {
        "method": None,
        "obj_type": "combat",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use Combat object API in 1.x",
        "custom": "combat_passthrough",
    },
    "doAreaCombatHealth": {
        "method": None,
        "obj_type": "combat",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use Combat object API in 1.x",
        "custom": "combat_passthrough",
    },
    "doTargetCombatMana": {
        "method": None,
        "obj_type": "combat",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use Combat object API in 1.x",
        "custom": "combat_passthrough",
    },
    "doAreaCombatMana": {
        "method": None,
        "obj_type": "combat",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use Combat object API in 1.x",
        "custom": "combat_passthrough",
    },
    "doTargetCombatCondition": {
        "method": None,
        "obj_type": "combat",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use Combat object API in 1.x",
        "custom": "combat_passthrough",
    },
    "doAreaCombatCondition": {
        "method": None,
        "obj_type": "combat",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use Combat object API in 1.x",
        "custom": "combat_passthrough",
    },

    "doPlayerSendOutfitWindow": {
        "method": "sendOutfitWindow",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doShowTextDialog": {
        "method": "showTextDialog",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerFeed": {
        "method": "feed",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: In 1.x, feeding uses condition system. Review this conversion.",
    },

    "getPlayerParty": {
        "method": "getParty",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerJoinParty": {
        "method": "joinParty",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
}

ITEM_FUNCTIONS = {
    "doRemoveItem": {
        "method": "remove",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },
    "doTransformItem": {
        "method": "transform",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },
    "doItemSetAttribute": {
        "method": "setAttribute",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },
    "doItemEraseAttribute": {
        "method": "removeAttribute",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },
    "doSetItemActionId": {
        "method": "setActionId",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },
    "doSetItemText": {
        "method": "setText",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },
    "doDecayItem": {
        "method": "decay",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Item",
    },
    "getItemName": {
        "method": "getName",
        "obj_type": "item",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "ItemType",
    },
}

# GAME / WORLD FUNCTIONS (static calls)

GAME_FUNCTIONS = {
    "doCreateItem": {
        "method": "createItem",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },
    "doCreateItemEx": {
        "method": "createItem",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
        "note": "-- TTT: doCreateItemEx replaced with Game.createItem",
    },
    "doCreateMonster": {
        "method": "createMonster",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },
    "doCreateNpc": {
        "method": "createNpc",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },
    "doSummonCreature": {
        "method": "createMonster",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
        "note": "-- TTT: doSummonCreature replaced with Game.createMonster. Review summon ownership.",
    },
    "broadcastMessage": {
        "method": "broadcastMessage",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },
    "getWorldTime": {
        "method": "getWorldTime",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },
    "getWorldUpTime": {
        "method": "getWorldUpTime",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },
    "getWorldCreatures": {
        "method": "getPlayers",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
        "note": "-- TTT: getWorldCreatures replaced. Use Game.getPlayers(), Game.getMonsters(), Game.getNpcs()",
    },
    "getPlayersOnline": {
        "method": "getPlayerCount",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Game",
    },
    "getPlayerByName": {
        "method": "getPlayerByName",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Player",
    },
    "getPlayerByNameWildcard": {
        "method": "getPlayerByName",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Player",
        "note": "-- TTT: Wildcard lookup not directly supported in 1.x",
    },
    "getCreatureByName": {
        "method": "getCreatureByName",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "Creature",
        "note": "-- TTT: Review - may need Game.getPlayers() + iterating",
    },

    "doSendMagicEffect": {
        "method": "sendMagicEffect",
        "obj_type": "position",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Position",
    },
    "doSendDistanceShoot": {
        "method": "sendDistanceEffect",
        "obj_type": "position",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Position",
    },
    "doSendAnimatedText": {
        "method": "sendAnimatedText",
        "obj_type": "position",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Position",
        "note": "-- TTT: doSendAnimatedText requires custom implementation in your server (see xtibia.com/topic/240213)",
    },

    "getTileItemById": {
        "method": "getItemById",
        "obj_type": "tile",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Tile",
    },
    "getTileItemByType": {
        "method": "getItemByType",
        "obj_type": "tile",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Tile",
    },
    "getTileThingByPos": {
        "method": "getTopVisibleThing",
        "obj_type": "tile",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Tile",
    },
    "getThingfromPos": {
        "method": "getTopVisibleThing",
        "obj_type": "tile",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Tile",
    },
    "getTilePzInfo": {
        "method": "hasFlag",
        "obj_type": "tile",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Tile",
        "note": "-- TTT: Use Tile(pos):hasFlag(TILESTATE_PROTECTIONZONE)",
    },
    "getTileInfo": {
        "method": "getGround",
        "obj_type": "tile",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Tile",
        "note": "-- TTT: getTileInfo replaced. Use Tile methods individually.",
    },
    "doCleanTile": {
        "method": "clean",
        "obj_type": "tile",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "Tile",
    },

    "getHouseByPlayerGUID": {
        "method": "getHouse",
        "obj_type": "game",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: In 1.x use player:getHouse() or House(houseId)",
        "custom": "house_lookup",
    },
    "setHouseOwner": {
        "method": "setOwnerGuid",
        "obj_type": "house",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "House",
    },
    "getHouseOwner": {
        "method": "getOwnerGuid",
        "obj_type": "house",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "House",
    },
    "getHouseName": {
        "method": "getName",
        "obj_type": "house",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "House",
    },
    "getHouseRent": {
        "method": "getRent",
        "obj_type": "house",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "House",
    },
    "getHouseEntry": {
        "method": "getExitPosition",
        "obj_type": "house",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "House",
    },
    "getHouseTown": {
        "method": "getTown",
        "obj_type": "house",
        "obj_param": 0,
        "drop_params": [0],
        "wrapper": "House",
    },

    "db.executeQuery": {
        "method": "query",
        "obj_type": "db",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "db",
    },
    "db.getResult": {
        "method": "storeQuery",
        "obj_type": "db",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "db",
    },
    "db.storeQuery": {
        "method": "storeQuery",
        "obj_type": "db",
        "obj_param": None,
        "drop_params": [],
        "static": True,
        "static_class": "db",
    },

    "getDistanceBetween": {
        "method": "getDistance",
        "obj_type": "position",
        "obj_param": 0,
        "drop_params": [0],
    },

    "doPlayerSetGroupId": {
        "method": "setGroup",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: In 1.x use player:setGroup(Group(groupId))",
    },
    "doPlayerSetRate": {
        "method": "setStamina",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: doPlayerSetRate removed. Check 1.x rate system.",
    },
    "registerCreatureEvent": {
        "method": "registerEvent",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "unregisterCreatureEvent": {
        "method": "unregisterEvent",
        "obj_type": "creature",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSave": {
        "method": "save",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSetStamina": {
        "method": "setStamina",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerStamina": {
        "method": "getStamina",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },

    "selfSay": {
        "method": "say",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: selfSay replaced. Use Npc():say() or NPC talk system.",
        "custom": "npc_self",
    },
    "doNpcSellItem": {
        "method": "sellItem",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use NPC shop system in 1.x",
        "custom": "npc_passthrough",
    },
    "doNpcBuyItem": {
        "method": "buyItem",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "note": "-- TTT: Use NPC shop system in 1.x",
        "custom": "npc_passthrough",
    },
    "getNpcCid": {
        "method": "getId",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "custom": "npc_get_self",
    },
    "getNpcName": {
        "method": "getName",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "custom": "npc_method_self",
    },
    "getNpcPos": {
        "method": "getPosition",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "custom": "npc_method_self",
    },
    "selfGetPosition": {
        "method": "getPosition",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "custom": "npc_method_self",
    },
    "selfMoveTo": {
        "method": "move",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "custom": "npc_action_self",
    },
    "selfTurn": {
        "method": "turn",
        "obj_type": "npc",
        "obj_param": None,
        "drop_params": [],
        "custom": "npc_action_self",
    },
    "doShowTextDialog": {
        "method": "showTextDialog",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "doPlayerSetTown": {
        "method": "setTown",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "note": "-- TTT: In 1.x use player:setTown(Town(townId))",
    },
    "getPlayerTown": {
        "method": "getTown",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
        "chain": ":getId()",
        "note": "-- TTT: returns Town object, auto-chained :getId()",
    },
    "doPlayerSetBalance": {
        "method": "setBankBalance",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
    "getPlayerBalance": {
        "method": "getBankBalance",
        "obj_type": "player",
        "obj_param": 0,
        "drop_params": [0],
    },
}

# Game-specific custom functions (PokeInvictus / Pokemon-specific)
# These require custom lib implementation in the target server
# They are flagged with TTT:STUB for easy grep and LLM targeting

STUB_FUNCTIONS = {
    "isWild": {
        "stub": "needs custom lib: checks if pokemon is wild (storage-based). Suggested: check creature storage value",
    },
    "isMega": {
        "stub": "needs custom lib: checks if pokemon is mega evolved. Suggested: check creature storage value",
    },
    "isGod": {
        "stub": "needs custom lib: checks player access level. Suggested: player:hasGroupFlag(PlayerFlag_IsAdmin)",
    },
    "getSubName": {
        "stub": "needs custom lib: reads pokemon subspecies name from custom storage",
    },
    "getRealCreatureName": {
        "stub": "needs custom lib: gets display name stripping suffixes",
    },
    "isSleeping": {
        "stub": "needs custom lib: checks sleeping condition via creature storage",
    },
    "doDanoWithProtect": {
        "stub": "needs custom lib: wraps doAreaCombatHealth/doTargetCombatHealth with protection logic",
    },
    "doDanoInTargetWithDelay": {
        "stub": "needs custom lib: delayed combat wrapper with addEvent",
    },
    "doCorrectString": {
        "stub": "needs custom lib: string normalization (trim, lower, etc.)",
    },
    "getCreatureDirectionToTarget": {
        "stub": "needs custom lib: computes direction from position delta",
    },
    "getDataInt": {
        "stub": "needs custom lib: reads integer from DB. Suggested: use db.storeQuery",
    },
    "getResult": {
        "stub": "needs custom lib: DB result helper. Suggested: use db.storeQuery result handling",
    },
    "doTeleportThingOk": {
        "stub": "needs custom lib: same as doTeleportThing but returns status boolean",
    },
    "doRegainSpeed": {
        "stub": "needs custom lib: restores speed. Suggested: creature:changeSpeed(+delta)",
    },
    "doMoveInAreaMulti": {
        "stub": "needs custom lib: moves items in area. No direct 1.x equivalent",
    },
    "doSendMsg": {
        "stub": "needs custom lib: broadcast helper. Suggested: wrapper around creature:say or sendTextMessage",
    },
    "getID": {
        "stub": "needs custom lib: returns item unique ID. Suggested: item:getUniqueId()",
    },
}

# Combine all mappings

TFS03_TO_1X = {}
TFS03_TO_1X.update(PLAYER_GETTERS)
TFS03_TO_1X.update(PLAYER_ACTIONS)
TFS03_TO_1X.update(ITEM_FUNCTIONS)
TFS03_TO_1X.update(GAME_FUNCTIONS)
TFS03_TO_1X.update(STUB_FUNCTIONS)
